# -*- coding: utf-8 -*-
"""Naive Byes Classifer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xaO6Gz-lN6QrsVYQja_kiwBgpfplAI1F
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
import warnings
warnings.filterwarnings('ignore')

data = '/content/drive/MyDrive/DATASET/adult.csv'
df = pd.read_csv(data, header=None , sep=',\s')
df.head()

df.shape

col_names = ['age', 'workclass', 'fnlwgt', 'education', 'education_num', 'marital_status', 'occupation', 'relationship',
             'race', 'sex', 'capital_gain', 'capital_loss', 'hours_per_week', 'native_country', 'income']
df.columns = col_names
df.columns

df.head()

df.info()

categorical = [var for var in df.columns if df[var].dtype=='O']
print(' There are {} categorical variables\n'. format(len(categorical)))
print('The categorical variables are : \n\n', categorical)

df[categorical].head()

df[categorical].isnull().sum()

for var in categorical:
  print(df[var].value_counts())

for var in categorical:
  print(df[var].value_counts()/float(len(df)))

df.workclass.unique()

df.workclass.value_counts()

df['workclass'].replace('?' , np.nan, inplace = True)

df.workclass.value_counts()

df.occupation.unique()

df.occupation.value_counts()

df['occupation'].replace('?' , np.nan, inplace = True)

df.occupation.value_counts()

df.native_country.unique()

df.native_country.value_counts()

df['native_country'].replace('?' , np.nan, inplace = True)

df.native_country.value_counts()

df[categorical].isnull().sum()

for var in categorical:
  print(var , 'contains' , len(df[var].unique()),'labels')

numerical = [ var for var in df.columns if df[var].dtype!='O']
print('There are {} numerical variables\n'.format(len(numerical)))
print('The numerical variables are :', numerical)

df[numerical].head()

df[numerical].isnull().sum()

"""## 8. Declare feature vector and target variable"""

X = df.drop(['income'], axis=1)
y = df['income']

"""##9. Split data into separate training and test set"""

# split X and y into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

X_train.shape, X_test.shape

"""##10. Feature Engineering"""

X_train.dtypes

# display categorical variables
categorical = [col for col in X_train.columns if X_train[col].dtypes == 'O']
categorical

# display numerical variables
numerical = [col for col in X_train.columns if X_train[col].dtypes != 'O']
numerical

# print percentage of missing values in the categorical variables in training set

X_train[categorical].isnull().mean()

# print categorical variables with missing data

for col in categorical:
    if X_train[col].isnull().mean()>0:
        print(col, (X_train[col].isnull().mean()))

# impute missing categorical variables with most frequent value

for df2 in [X_train, X_test]:
    df2['workclass'].fillna(X_train['workclass'].mode()[0], inplace=True)
    df2['occupation'].fillna(X_train['occupation'].mode()[0], inplace=True)
    df2['native_country'].fillna(X_train['native_country'].mode()[0], inplace=True)

# check missing values in categorical variables in X_train

X_train[categorical].isnull().sum()

# check missing values in categorical variables in X_test
X_test[categorical].isnull().sum()

# check missing values in X_train

X_train.isnull().sum()

# check missing values in X_test

X_test.isnull().sum()

# print categorical variables
categorical

X_train[categorical].head()

!pip install category_encoders

import category_encoders as ce

encoder = ce.OneHotEncoder(cols=['workclass', 'education', 'marital_status', 'occupation', 'relationship',
                                 'race', 'sex', 'native_country'])
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

X_train.head()

X_train.shape

X_test.head()

X_test.shape

"""## 11. Feature Scaling"""

cols = X_train.columns

from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_train = pd.DataFrame(X_train, columns=[cols])

X_test = pd.DataFrame(X_test, columns=[cols])

X_train.head()

"""## 12. Model training"""

# train a Gaussian Naive Bayes classifier on the training set
from sklearn.naive_bayes import GaussianNB

# instantiate the model
gnb = GaussianNB()

# fit the model
gnb.fit(X_train, y_train)

"""##13. Predict the results"""

y_pred = gnb.predict(X_test)
y_pred

"""## 14. Check accuracy score"""

from sklearn.metrics import accuracy_score
print('Model accuracy score: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

y_pred_train = gnb.predict(X_train)
y_pred_train

print('Training-set accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train)))

# Check for overfitting and underfitting
# print the scores on training and test set

print('Training set score: {:.4f}'.format(gnb.score(X_train, y_train)))
print('Test set score: {:.4f}'.format(gnb.score(X_test, y_test)))

# check class distribution in test set
y_test.value_counts()

# check null accuracy score

null_accuracy = (7407/(7407+2362))
print('Null accuracy score: {0:0.4f}'. format(null_accuracy))

# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix\n\n', cm)
print('\nTrue Positives(TP) = ', cm[0,0])
print('\nTrue Negatives(TN) = ', cm[1,1])
print('\nFalse Positives(FP) = ', cm[0,1])
print('\nFalse Negatives(FN) = ', cm[1,0])

# visualize confusion matrix with seaborn heatmap

cm_matrix = pd.DataFrame(data=cm, columns=['Actual Positive:1', 'Actual Negative:0'],
                                 index=['Predict Positive:1', 'Predict Negative:0'])

sns.heatmap(cm_matrix, annot=True, fmt='d', cmap='YlGnBu')

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))